### ISSUE TITLE
Cannot copy to clipboard from text entry box

### ISSUE THREAD

**Issue by Daeraxa** [squidowl/halloy#156]
- Type something in the text entry box (`Send message...`)
- Select with mouse or keyboard
- Ctrl + C
- Nothing is copied to clipboard

Noticed on Windows but haven't checked Linux yet.
Halloy #4547ba1

**Comment by tarkah** [comment]
Oops, fixed with #159

**Comment by tribals** [comment]
Still can't neither copy, nor paste. https://scoop.sh/#/apps?q=halloy&id=3823a7a447a915f93c24a749dab6e256304c89b1
