### ISSUE TITLE
High CPU usage when window not visible

### ISSUE THREAD

**Issue by Okkonen-GitHub** [squidowl/halloy#781]
I'm getting crazy high cpu usage on Sway (wayland) when the app is not visible. Halloy will take 80 % of one cpu core and Sway's cpu usage jumps to 40 % too. Note that this only occurs when the window is completely not visible (so just unfocusing doesn't trigger this behaviour)
It also does this when I pop out a chat, if either window is not visible.

## System
- Halloy: 2025.1.1
- OS: Artix Linux (rolling)
- DE/WM: Sway
- Arch: amd64

**Comment by Exagone313** [comment]
I can reproduce. When the window is focused on a workspace, the halloy process uses about 3% CPU with some random spikes of 30% or 70%. When the window is on another workspace, it constantly uses at least 80% CPU, usually 130%.

**Comment by Exagone313** [comment]
Could be a dup of #589 though it says *several hours* and we reproduce instantly.

**Comment by casperstorm** [comment]
I believe https://github.com/iced-rs/iced/issues/1810 is the upstream issue.

**Comment by Exagone313** [comment]
I can confirm that after upsetting `WAYLAND_DISPLAY` (thus forcing the usage of Xwayland) the CPU issue disappears.

**Comment by englut** [comment]
I'm getting the CPU issue too now. With both [AUR package](https://aur.archlinux.org/packages/halloy) and the latest commit. Testing the flatpak version of Halloy, it seems unaffected by this issue and still uses Wayland.

**Comment by casperstorm** [comment]
This has been fixed in [2025.4](https://github.com/squidowl/halloy/releases/tag/2025.4)

**Comment by Okkonen-GitHub** [comment]
I regret to inform to you that I am still experiencing the same issue using the version 2025.4 via the [AUR](https://aur.archlinux.org/packages/halloy).

Using this as a temporary fix works for me too:

> I can confirm that after unsetting `WAYLAND_DISPLAY` (thus forcing the usage of Xwayland) the CPU issue disappears.
